### ISSUE TITLE
Porting to Kotlin

### ISSUE THREAD

**Issue by SchoolGuy** [kekru/struktogrammeditor#10]
Java is great but we could try to port this to Kotlin to get systematically rid of NPEs which happen often in Java.

Here is a german article which decsribes the differences of Java and Kotlin on the surface relatively good: https://www.dev-insider.de/kotlin-oder-doch-lieber-java-a-891486/

P.S.: As a dev I am in favor of Kotlin, as a packager for openSUSE I hate it because it makes my life a littlebit harder but that shouldn't be a factor in the final decision here. I will probably will package it anyway.

**Comment by kekru** [comment]
I did not yet work with Kotlin yet, and don't have the time to get started.  
So I would not like to move this project to Kotlin.  

I don't think NPEs are a big problem in Java. If you have experience with Java, you know where to put Nullchecks.

We have other problems in this code base than NPEs.  
This project is one of my first Java projects, ten years old. First step would be to restructure the code with clean code principles ;)
